name: merge a pull request with message and body (optional)
on: [pull_request, pull_request_review, status]
jobs:
   automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: sudo-bot/action-pull-request-merge@v1.1.
        env:
            github-token: ${{ secrets.GITHUB_TOKEN }}
           
